modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]]

modId="nubmod" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Nub Mod"

logoFile="examplemod.png" #optional

credits="Thanks for this example mod goes to Java"

authors="NUBZRCOOL" #optional

description='''
My First Mod!
'''
[[dependencies.examplemod]] #optional

    modId="forge"

    mandatory=true

    versionRange="[40,)" 

    ordering="NONE"

    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
